# Generated by Django 5.2.6 on 2025-09-14 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCultural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ubicacion_texto', models.CharField(max_length=255)),
                ('publicado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_creados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
