# Generated by Django 5.2.6 on 2025-09-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventocultural',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
    ]
