# Generated by Django 5.2.6 on 2025-09-29 01:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Rango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Rangos',
            },
        ),
        migrations.CreateModel(
            name='MensajePropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asunto', models.CharField(max_length=255)),
                ('cuerpo', models.TextField()),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('leido', models.BooleanField(default=False)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mensajes de Propietarios',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del Negocio')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('address_text', models.CharField(max_length=255, verbose_name='Dirección')),
                ('hours', models.CharField(blank=True, max_length=100, null=True, verbose_name='Horario')),
                ('foto_principal', models.ImageField(blank=True, null=True, upload_to='negocios_fotos/', verbose_name='Foto Principal')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('paquetes_turismo', models.TextField(blank=True, null=True, verbose_name='Paquetes de Turismo')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Enlace de video (YouTube, Vimeo, etc.)')),
                ('propietario_contacto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Información de Contacto del Propietario')),
                ('categoria_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locales.categoria', verbose_name='Categoría')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios_creados', to=settings.AUTH_USER_MODEL)),
                ('propietario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='negocios_propios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.negocio')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('comentario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calificacion', to='locales.comentario')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.negocio')),
            ],
            options={
                'verbose_name_plural': 'Calificaciones',
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='avatares/default_avatar.png', upload_to='avatares/')),
                ('biografia', models.TextField(blank=True, max_length=500, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilusuario', to=settings.AUTH_USER_MODEL)),
                ('rango', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locales.rango')),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('ingredientes', models.TextField(help_text='Lista de ingredientes, separados por comas o saltos de línea.')),
                ('pasos', models.TextField(help_text='Instrucciones paso a paso.')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='recetas_imagenes/')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recetas',
            },
        ),
        migrations.CreateModel(
            name='ReclamoNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contrato_pdf', models.FileField(blank=True, null=True, upload_to='reclamos/', verbose_name='Documento de propiedad')),
                ('mensaje', models.TextField(verbose_name='Mensaje para el administrador')),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.negocio', verbose_name='Negocio a reclamar')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que reclama')),
            ],
            options={
                'verbose_name_plural': 'Reclamos de Negocio',
            },
        ),
        migrations.CreateModel(
            name='Relato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('image', models.ImageField(blank=True, null=True, upload_to='relatos_images/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReporteComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locales.comentario')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Reportes de Comentario',
            },
        ),
        migrations.CreateModel(
            name='SaberPopular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='saberes_imagenes/')),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Saberes Populares',
            },
        ),
        migrations.CreateModel(
            name='SugerenciaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=100)),
                ('ubicacion_texto', models.CharField(max_length=255, verbose_name='Ubicación')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('fecha_sugerencia', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('foto_referencia', models.ImageField(blank=True, null=True, upload_to='sugerencias_fotos/')),
                ('foto_aprobada', models.BooleanField(default=False)),
                ('categoria_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locales.categoria', verbose_name='Categoría sugerida')),
                ('sugerido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sugerencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sugerencias de Negocio',
                'ordering': ['-fecha_sugerencia'],
            },
        ),
    ]
