# Generated by Django 5.2.6 on 2025-09-29 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='is_turismo',
            field=models.BooleanField(default=False, verbose_name='Es un negocio de turismo'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Página Web'),
        ),
    ]
