# Generated by Django 5.2.6 on 2025-09-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='rango',
            field=models.CharField(choices=[('visitante', 'Visitante'), ('colaborador', 'Colaborador'), ('admin', 'Administrador')], default='visitante', max_length=20),
        ),
    ]
