# Generated by Django 5.2.6 on 2025-09-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0002_negocio_email_negocio_is_turismo_negocio_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencianegocio',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='sugerencianegocio',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
