# Generated by Django 5.2.6 on 2025-09-14 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_eventocultural_receta_saberpopular'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receta',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='saberpopular',
            name='autor',
        ),
        migrations.DeleteModel(
            name='EventoCultural',
        ),
        migrations.DeleteModel(
            name='Receta',
        ),
        migrations.DeleteModel(
            name='SaberPopular',
        ),
    ]
