# Generated by Django 5.2.6 on 2025-09-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0003_alter_sugerencianegocio_latitud_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugerencianegocio',
            name='latitud',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='sugerencianegocio',
            name='longitud',
            field=models.DecimalField(blank=True, decimal_places=12, max_digits=15, null=True),
        ),
    ]
