# Generated by Django 5.2.6 on 2025-09-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0005_reportecomentario_delete_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales.comentario'),
        ),
    ]
