# Generated by Django 5.2.6 on 2025-09-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0006_calificacion_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='category',
            field=models.CharField(choices=[('Restaurante', 'Restaurante'), ('Hotel', 'Hotel'), ('Artesania', 'Artesanía'), ('Museo', 'Museo'), ('limpieza', 'limpieza'), ('Diseño gráfico', 'Diseño gráfico'), ('Repostería', 'Repostería'), ('Joyería', 'Joyeria'), ('Gimnasio', 'Gimnasio'), ('Coaching', 'Coaching'), ('Tecnologia', 'Tecnologia'), ('Clinica', 'Clinica'), ('Bar', 'Bar'), ('Barberia', 'Barberia'), ('Tiendas de ropa', 'Tiendas de ropa'), ('Salon de Belleza', 'Salon de Belleza'), ('Carpinteria', 'Carpinteria'), ('Zapateria', 'Zapateria'), ('Bodega', 'Bodega')], max_length=50),
        ),
    ]
