# Generated by Django 5.2.6 on 2025-09-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0007_alter_negocio_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencianegocio',
            name='categoria_negocio',
            field=models.CharField(choices=[('Sin especificar', 'Sin especificar'), ('Restaurante', 'Restaurante'), ('Hotel', 'Hotel'), ('Artesania', 'Artesanía'), ('Museo', 'Museo'), ('limpieza', 'limpieza'), ('Diseño gráfico', 'Diseño gráfico'), ('Repostería', 'Repostería'), ('Joyería', 'Joyeria'), ('Gimnasio', 'Gimnasio'), ('Coaching', 'Coaching'), ('Tecnologia', 'Tecnologia'), ('Clinica', 'Clinica'), ('Bar', 'Bar'), ('Barberia', 'Barberia'), ('Tiendas de ropa', 'Tiendas de ropa'), ('Salon de Belleza', 'Salon de Belleza'), ('Carpinteria', 'Carpinteria'), ('Zapateria', 'Zapateria'), ('Bodega', 'Bodega')], default='Sin especificar', max_length=50),
        ),
        migrations.AddField(
            model_name='sugerencianegocio',
            name='foto_referencia',
            field=models.ImageField(blank=True, null=True, upload_to='sugerencias/'),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='category',
            field=models.CharField(choices=[('Sin especificar', 'Sin especificar'), ('Restaurante', 'Restaurante'), ('Hotel', 'Hotel'), ('Artesania', 'Artesanía'), ('Museo', 'Museo'), ('limpieza', 'limpieza'), ('Diseño gráfico', 'Diseño gráfico'), ('Repostería', 'Repostería'), ('Joyería', 'Joyeria'), ('Gimnasio', 'Gimnasio'), ('Coaching', 'Coaching'), ('Tecnologia', 'Tecnologia'), ('Clinica', 'Clinica'), ('Bar', 'Bar'), ('Barberia', 'Barberia'), ('Tiendas de ropa', 'Tiendas de ropa'), ('Salon de Belleza', 'Salon de Belleza'), ('Carpinteria', 'Carpinteria'), ('Zapateria', 'Zapateria'), ('Bodega', 'Bodega')], max_length=50),
        ),
    ]
