# Generated by Django 5.2.6 on 2025-09-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0008_sugerencianegocio_categoria_negocio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencianegocio',
            name='foto_aprobada',
            field=models.BooleanField(default=False),
        ),
    ]
