# Generated by Django 5.2.5 on 2025-09-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0009_sugerencianegocio_foto_aprobada'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugerencianegocio',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sugerencianegocio',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='negocio',
            name='category',
            field=models.CharField(choices=[('Sin especificar', 'Sin especificar'), ('Restaurante', 'Restaurante'), ('Hotel', 'Hotel'), ('Artesania', 'Artesanía'), ('Museo', 'Museo'), ('Limpieza', 'Limpieza'), ('Diseño gráfico', 'Diseño gráfico'), ('Repostería', 'Repostería'), ('Joyería', 'Joyería'), ('Gimnasio', 'Gimnasio'), ('Coaching', 'Coaching'), ('Tecnología', 'Tecnología'), ('Clínica', 'Clínica'), ('Bar', 'Bar'), ('Barbería', 'Barbería'), ('Tiendas de ropa', 'Tiendas de ropa'), ('Salón de Belleza', 'Salón de Belleza'), ('Carpintería', 'Carpintería'), ('Zapatería', 'Zapatería'), ('Bodega', 'Bodega'), ('Turismo', 'Turismo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='sugerencianegocio',
            name='categoria_negocio',
            field=models.CharField(choices=[('Sin especificar', 'Sin especificar'), ('Restaurante', 'Restaurante'), ('Hotel', 'Hotel'), ('Artesania', 'Artesanía'), ('Museo', 'Museo'), ('Limpieza', 'Limpieza'), ('Diseño gráfico', 'Diseño gráfico'), ('Repostería', 'Repostería'), ('Joyería', 'Joyería'), ('Gimnasio', 'Gimnasio'), ('Coaching', 'Coaching'), ('Tecnología', 'Tecnología'), ('Clínica', 'Clínica'), ('Bar', 'Bar'), ('Barbería', 'Barbería'), ('Tiendas de ropa', 'Tiendas de ropa'), ('Salón de Belleza', 'Salón de Belleza'), ('Carpintería', 'Carpintería'), ('Zapatería', 'Zapatería'), ('Bodega', 'Bodega'), ('Turismo', 'Turismo')], default='Sin especificar', max_length=50),
        ),
        migrations.AlterField(
            model_name='sugerencianegocio',
            name='ubicacion_texto',
            field=models.CharField(max_length=500),
        ),
    ]
