# Generated by Django 5.2.6 on 2025-09-26 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0010_alter_negocio_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='negocio',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locales.categorianegocio'),
        ),
        migrations.AlterField(
            model_name='sugerencianegocio',
            name='categoria_negocio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='locales.categorianegocio'),
        ),
    ]
